version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: civis_postgres_container
    environment:
      POSTGRES_PASSWORD: ffg_jpmc_civis
      POSTGRES_USER: ffg
      POSTGRES_DB: civis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
