"""Creating document type and assessment area tables

Revision ID: 0949d13c00ec
Revises:
Create Date: 2025-06-05 04:14:24.881800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0949d13c00ec'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'assessment_area',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('assessment_title', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_assessment_area_assessment_title'),
        'assessment_area',
        ['assessment_title'],
        unique=True,
    )
    op.create_index(
        op.f('ix_assessment_area_id'), 'assessment_area', ['id'], unique=False
    )
    op.create_table(
        'document_type',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('document_type_name', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_document_type_document_type_name'),
        'document_type',
        ['document_type_name'],
        unique=True,
    )
    op.create_index(op.f('ix_document_type_id'), 'document_type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_type_id'), table_name='document_type')
    op.drop_index(
        op.f('ix_document_type_document_type_name'), table_name='document_type'
    )
    op.drop_table('document_type')
    op.drop_index(op.f('ix_assessment_area_id'), table_name='assessment_area')
    op.drop_index(
        op.f('ix_assessment_area_assessment_title'), table_name='assessment_area'
    )
    op.drop_table('assessment_area')
    # ### end Alembic commands ###
