"""Prompt, AssesmentArea and DocumentType schema updated

Revision ID: 76733c59ca0e
Revises: 
Create Date: 2025-06-07 23:12:19.636237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76733c59ca0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_area',
    sa.Column('assessment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('document_type',
    sa.Column('doc_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_type_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('doc_type_id')
    )
    op.create_table('prompt',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('prompt_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt')
    op.drop_table('document_type')
    op.drop_table('assessment_area')
    # ### end Alembic commands ###
