"""AssesmentArea and Prompt schema updated to include relationship

Revision ID: e018bbf19ddb
Revises: b19b30e8e9be
Create Date: 2025-06-10 21:45:04.175468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e018bbf19ddb'
down_revision: Union[str, None] = 'b19b30e8e9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_area_prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_on', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment_area.assessment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.prompt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'prompt_id', name='_assessment_prompt_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_area_prompt')
    # ### end Alembic commands ###
